import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig(({ mode }) => {
  // 載入環境變數
  const env = loadEnv(mode, process.cwd(), '')
  return {
    plugins: [react()],
    base: '/YOUR_REPO_NAME/', // 記得改名
    define: {
      // 這行讓程式碼裡的 process.env.API_KEY 在打包後能讀取到值
      'process.env.API_KEY': JSON.stringify(env.API_KEY)
    }
  }
})
